/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Logins;
import javax.swing.JOptionPane;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import Logins.Booking_Frame;
import Logins.newRegxFrame;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import com.sun.jndi.ldap.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import java.util.*;
import java.io.*;
                                         
/**
 *
 * @author ashi sinha
 */
class Customer implements Serializable
{
    String name,username,password,phone_number,email_id;
    Double wallet_money;
    static ArrayList<Customer> arr= new ArrayList<Customer>();
    Customer(){}
    Customer(String a,String b,String c,double d,String e,String f)
    {
         name=a;
         username=b;
         password=c;
         wallet_money=d;
         phone_number=e;
         email_id=f;
         arr.add(this);
         String filename= "data1";
         try{
         ObjectOutputStream os= new ObjectOutputStream(new FileOutputStream(filename));
         os.writeObject(arr);
         os.close();
         }
         catch(Exception ae){}
         //System.out.println("in constructor:"+arr);
    }
   /* public void createNew(){
        Customer one= new Customer("Ishika Kumar","Ishika","Kumar",0.0,"","");
        Customer two= new Customer("Ashi Sinha","Ashi","Sinha",0.0,"","");
        Customer three= new Customer("","","",0.0,"","");
        Customer four= new Customer("","","",0.0,"","");
        Customer five= new Customer("","","",0.0,"","");
        String filename= "C:\\Users\\PRANAVI MARRIPUDI\\Desktop\\Customer.ser";
        try{
            
            ObjectOutputStream os= new ObjectOutputStream(new FileOutputStream(filename));
            os.writeObject(one);
            os.writeObject(two);
            os.writeObject(three);
            os.writeObject(four);
            os.writeObject(five);
            

            os.close();
        }
        catch(Exception ae){
         System.out.println("Not adding");
        }
        
    }*/
        /*public ArrayList<Customer> getList(){
            return arr;
        }*/
    }

public class Login extends javax.swing.JFrame {
    static String user;
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jUsername1 = new javax.swing.JLabel();
        jPassword1 = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        jUsername = new javax.swing.JTextField();
        jloginbtn = new javax.swing.JButton();
        jresetbtn = new javax.swing.JButton();
        jexitbtn = new javax.swing.JButton();
        jnewbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1400, 700));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 72)); // NOI18N
        jLabel2.setText("Welcome!!");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 10, true));

        jUsername1.setBackground(new java.awt.Color(204, 204, 255));
        jUsername1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jUsername1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jUsername1.setText("Username");
        jUsername1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));
        jUsername1.setOpaque(true);

        jPassword1.setBackground(new java.awt.Color(204, 204, 255));
        jPassword1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPassword1.setText("Password");
        jPassword1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));
        jPassword1.setOpaque(true);

        jPassword.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPassword.setText("0");
        jPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));

        jUsername.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jUsername.setText("0");
        jUsername.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));
        jUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUsernameActionPerformed(evt);
            }
        });

        jloginbtn.setBackground(new java.awt.Color(204, 204, 255));
        jloginbtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jloginbtn.setText("Login");
        jloginbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));
        jloginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jloginbtnActionPerformed(evt);
            }
        });

        jresetbtn.setBackground(new java.awt.Color(204, 204, 255));
        jresetbtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jresetbtn.setText("Reset");
        jresetbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));
        jresetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jresetbtnActionPerformed(evt);
            }
        });

        jexitbtn.setBackground(new java.awt.Color(204, 204, 255));
        jexitbtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jexitbtn.setText("Exit");
        jexitbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));
        jexitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jexitbtnActionPerformed(evt);
            }
        });

        jnewbtn.setBackground(new java.awt.Color(204, 204, 255));
        jnewbtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jnewbtn.setText("New User Registration");
        jnewbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));
        jnewbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnewbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPassword1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jUsername1, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                    .addComponent(jloginbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jresetbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(jexitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(103, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jnewbtn)
                .addGap(200, 200, 200))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUsername1)
                    .addComponent(jUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPassword1)
                    .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jloginbtn)
                    .addComponent(jresetbtn)
                    .addComponent(jexitbtn))
                .addGap(41, 41, 41)
                .addComponent(jnewbtn)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel2)))
                .addContainerGap(766, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addContainerGap(237, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jnewbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnewbtnActionPerformed
        newRegxFrame i= new newRegxFrame();
        i.setVisible(true);
        
        
    }//GEN-LAST:event_jnewbtnActionPerformed
    public String getUser(){
        return user;
    }
    private void jexitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jexitbtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jexitbtnActionPerformed

    private void jresetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jresetbtnActionPerformed
        jUsername.setText(null);
        jPassword.setText(null);
        
        
    }//GEN-LAST:event_jresetbtnActionPerformed

    private void jloginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jloginbtnActionPerformed
        boolean err1=false;
       String pass= jPassword.getText();
       user= jUsername.getText();
       
       String f="data1";
       ArrayList<Customer> a1= new ArrayList<>();
       try{
       FileInputStream fis= new FileInputStream(f);
       ObjectInputStream ois=new ObjectInputStream(fis);
       a1= (ArrayList<Customer>)ois.readObject();
       ois.close();
       fis.close();
        }
       catch(Exception e){}
        if(pass.equals('0') || pass.equals(" ")) err1= true;
        if(user.equals('0') || user.equals(" ")) err1= true;
        if(err1== true){
            JFrame fram = new JFrame("JOptionPane showMessageDialog example");
            JOptionPane.showMessageDialog(fram,"Invalid Credentials");
            System.exit(0);
        }
       int log=0;
       try{
       //ArrayList<Customer> a1= c.getList();
       System.out.println(a1);
       
       for(Customer a: a1){
            if((a.username).equals(user) && (a.password).equals(pass)){
                System.out.println("My Username:"+a.username);
                log=1;
                Booking_Frame i= new Booking_Frame();
                i.setVisible(true);
                this.setVisible(false);
                break;
            }  
        }
        if(log==0){
            //CloseMe();
            JFrame fram = new JFrame("JOptionPane showMessageDialog example");
            JOptionPane.showMessageDialog(fram,"User Not Registered!");
            
            newRegxFrame n= new newRegxFrame();
            n.setVisible(true);
            this.setVisible(false);
            
        }
       
       } 
       catch(Exception e){}
      
           
           
       
    }//GEN-LAST:event_jloginbtnActionPerformed

    private void jUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUsernameActionPerformed
   
    public void CloseMe(){
        WindowEvent meClose= new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(meClose);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        Customer one= new Customer("Ishika Kumar","Ishika","Kumar",300,"123455","ishi@gmail.com");
        Customer two= new Customer("Ashi Sinha","Ashi","Sinha",400,"123456","ashi@gmail.com");
        Customer three= new Customer("Meganaa Reddy","Meganaa","Reddy",123,"123457","mega@gmail.com");
        Customer four= new Customer("Harry Potter","Harry","Potter",299,"123458","harry@gmail.com");
        Customer five= new Customer("Katniss Everdeen","Katniss","Everdeen",450,"123445","katniss@gmail.com");
        
        System.out.println(Customer.arr);
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       // ArrayList<Customer> arr= new ArrayList<Customer>();
        /* Create and display the form */
        /*Customer Pranavi=new Customer("Pranavi","Pranavi","Marripudi","350","9010005800","pranavi@gmail.com");
        Customer Ashi=new Customer("Ashi","Ashi","Sinha","250","1234567890","ashi@gmail.com");
        ArrayList<Customer> aList=new ArrayList<Customer>();*/
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JLabel jPassword1;
    private javax.swing.JTextField jUsername;
    private javax.swing.JLabel jUsername1;
    private javax.swing.JButton jexitbtn;
    private javax.swing.JButton jloginbtn;
    private javax.swing.JButton jnewbtn;
    private javax.swing.JButton jresetbtn;
    // End of variables declaration//GEN-END:variables
   
    private void systemExit(){
    WindowEvent winCloseing= new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
            }
}
